hash-format = "sha256"

[[files]]
file = "mods/carry-on.pw.toml"
hash = "35b547f436644b0b5e08f36386fcf16e76616f0ab772c5c9bd1196accebd223b"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "0e073702f4562edac6258fd01f8b921628adf48fdd7e70209d93f4978753a0ce"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "717d8ac591dba59be4767a179e1359747561e54ccfcac42161fd6bf54339a78b"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "b98e0aca52ce8d08ee8df7177886589511b8bca779af078a6ff4837e814bccf4"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "da925d1159906a6c993fa4be167a48ae350d77daa1950a68135bf56c4e0dbb62"
metafile = true

[[files]]
file = "mods/cut-through.pw.toml"
hash = "a631c57fe299407992eded731b62bfe0ff8c9909337be88e52a50c4e68f0a42b"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "b7f3af0e77e5a5a32d5c8a4884e6e3792e418e10119bdfa9f7416da3e7000c2e"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "05c4bab9b066b825a39ea67731ff5af15dfae112e1a7b17542f518bf72dd27a7"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "0345fbfa8542b5ec84535fe2aff0f5cc4e801ecc337f926d4e2310b53f458569"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/fadeless.pw.toml"
hash = "a298b009def16625cf21d843be7b10820fe8c4731563b60169fbe78b76e9b0be"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "d74f72f3bf13c4ef7d60b6e2defecd3c7af77ed9be7764cf1ed10ea1fd707a1f"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "4105db403a4d910ac628d73a2cafdb9242d5f59c7b53e5b984fbb2fceb7cd3c5"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "fecd2e19a6afd8109bb6cfc281d158e3f7a5d6646a99340e2ece5d1aaece4edc"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "a077e0482f50add9ef20e962a7939aa678583cb3f354fb6b6124219badafdd4d"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "6a9a36e5b6df0459227d4c67760fab573d363f43e252a071c139cc576ff15588"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "cb330220512be399e4423c39f01f56f8bc413f15b0b5a7fa8079699bcdd133bc"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "84957275e9dc6f07f4244ce3303536e3d73b0e72eb1696ccd024168a52c29c98"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "9946fd3c2a85099bb68cff8a2168601c3f1c7879fc42d018171c7cf5f25693d2"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "802981efce132e93b99352dacae410bf7b3e356f2e9de14b0ff9cea0beb31bb9"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "70d7b2bca719eca2b3a1447228b868abdc633c38121652d49f4e34380c44339d"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "d3d3ebf53454b237e6ac91a6e3dc5fd34bfeefcf0714a11bfadd3e1488161772"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "e674752dd4dd07c33d9b94f6e19c15ef893c356c3c5ed77aeaf35cf6d2325130"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
hash = "d3ad1a85a4b58934658b7034ef8f670277591106fbe6488f05a0402ab01a5112"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "bedbd2675abf6bdb06c80570ba63d88e08caf7bb431d01e446d8770a5c62a9fb"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "ad2c2880cd91b5d927f3bfdba657189997cdd6dd30f46ee0d969a68de2bb2ad8"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "5ae220cfbb26641c68740ad0166c78f353680886fc28087e63bf07280a47ddbb"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "6cc155f0633b2187f5bc71357ab1d82c1d49f9592bcbd73191ec1001c98c342b"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "a2f4d9dda96c16714c36b3ad813e1d720dd6d8d4bf87e5c0bbc7bf54ed62540e"
metafile = true

[[files]]
file = "mods/skinrestorer.pw.toml"
hash = "f9ad248cda9947bf9336af6cb6537f4533ca79325128fbb22999fb19eaea22f5"
metafile = true

[[files]]
file = "mods/skinshuffle.pw.toml"
hash = "2d407ac870c9f5b4f651c7e98710d001a0a1887e94fc575778306770e2f40faa"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "bb7064282571976ed2bbe266bcf5e525d6d661aeea89649e4d604327973cf92d"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "279ea1bb4b776be9176fe34416e2132e37abfce4483def54177091cc0f2faade"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "831c41448bccb5bb8f1f68a76321e7da7988b218e9694f432d952f98ac184640"
metafile = true

[[files]]
file = "mods/universal-graves.pw.toml"
hash = "ed9329edc09aae7041d14e6f68563b9235a10163e4fc9e4e31d5a2d81883845e"
metafile = true

[[files]]
file = "mods/vanilla-refresh.pw.toml"
hash = "c747d8ec64328f2722166ac62ea371cd5becf82fa4b8012a679092649046f5b4"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "64f90fd9619a092a8a5493d6ad9605bc5fec13f50f02feef1dcf47c9496a80bd"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true
