hash-format = "sha256"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "bd0848389894ffe9850efb36210060ff0ac3cc31c74af7f80a897de05df4caa2"
metafile = true

[[files]]
file = "mods/a-good-place.pw.toml"
hash = "21274e0ad1dba39400ca748b092c3782166000dc3906a14833c74ab6c02673ef"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "42075a1e29aa311565c701e92d4bc2b7263a1f4f60c4be38eb55de1a289ee3e0"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "1102440dd2533ba3a154419bb95ff1f81b858201eb0c44d2a2eea486c74e565a"
metafile = true

[[files]]
file = "mods/better-combat.pw.toml"
hash = "d8f4cdc8afe5541c4e2da796f9fb04d3f60bb24a7c79762eb6df5e0d7831e7eb"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "6a492387f6348192bcb9e2ee15f9be142100648ce60080a75f980185cb66ee13"
metafile = true

[[files]]
file = "mods/centered-crosshair.pw.toml"
hash = "a67f5aabcc83e6f8af0ea1a775b6e25c96eee4acda5803de1fd986b268522976"
metafile = true

[[files]]
file = "mods/clientsort.pw.toml"
hash = "bc049c32a9f0a8740f192d2db7c32be5e6c61659062b436425585cf8c1101fbf"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "446c173c87b7908daee86b0dee89c6b628c77beb7a0bc091ff5252b7c0062080"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "fe84e2227c405bf9b735f01f307a01768784b9d49df82a13ecda3d3b6d198507"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "4f97764f3cb4c74f84afbe32cf8a1d2cefecda129c0f1441906562dcb8f2b8cb"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "eecdc8127f69c74ff55fd183d1f1d7d5ef3e714d73845a239fe9e086147a67b1"
metafile = true

[[files]]
file = "mods/coolrain.pw.toml"
hash = "cbdc8e983e7abf04500a44670df0826934add70851cf83abdbf064f9802773ee"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "41440aa391c6fb6ba275a47a78c4353fb5a2e4a76b2cd8d91e7751c7507a2637"
metafile = true

[[files]]
file = "mods/eating-animation.pw.toml"
hash = "cc46728d8879ff5ab1e00f17bb63bacaf30ea2699bb692c0ca5e084572ae3e8e"
metafile = true

[[files]]
file = "mods/effective.pw.toml"
hash = "2a421f249e7022255938fafdebf4a9d6490d62aecbabd48a9e9a3e52aacd4d0b"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "dde1c3036a0cc2c280e2254a5ffd647fbae47dd72c77dd564f35d791d6d21709"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "1fbcec6fae4237b80bf2becfc06fb52a49512821f402b5928b1e2533c73b3142"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "2ada3ac958fb2beff2e913d3094a06cab1b6a794de0e4132b014437d409af397"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "446f8047ee9168b65fe9d4600f82cb915c7aa0d0f049a344177ba340a5b93a8a"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/fadeless.pw.toml"
hash = "8edccc863207b12776be8207dbd0fe0c4f74b8d7a99f215a529695ce7cb3ac4b"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "9fb4d588bd578e2f16a9605ff6303872130b36ccb0fdfff98bd7274da94f91b9"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "238b3ceb4214a682480ce00eefae5d34efa299ff6ff667e4b2f2ed503c6e76ee"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "a1f1206514a1311c556b5e5542dac4acc1d239c9dc6120efe7b7495245376cfb"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "37e14a7a0b033feafd7fc1cb82842c128b1b2f2053dd1d11206834d7fcc6f597"
metafile = true

[[files]]
file = "mods/immersive-hotbar.pw.toml"
hash = "dee4bcf007803851b681b84daffe287aa3299a51b80ef5662be7407f65488b41"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "5284f6d141a990f4ea021c12b851e07102f5cb22743cf7b33be6ad2eb4c8d3f5"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "6492b21e2a58e97ab65ff384db18606ce317ea3b78fad7051e6e34899fe8e85b"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "76a2560989102413693bbfbea83570287b3dce4f6ed40dc69aacbd3268633fe7"
metafile = true

[[files]]
file = "mods/jump-over-fences.pw.toml"
hash = "0db15f56207814686e16b3e33505d910e8294c2acf393762caba6ec004b7d61b"
metafile = true

[[files]]
file = "mods/labels.pw.toml"
hash = "a1905763f6120a084eb348dbd512deb8eb6fb18cb5635db094937483dbc4eea0"
metafile = true

[[files]]
file = "mods/leave-my-bars-alone.pw.toml"
hash = "b0d31dcffb5f44ec5f63507f6bcaca7edbadf2145b57d51fb491480e16c36d74"
metafile = true

[[files]]
file = "mods/libjf.pw.toml"
hash = "10d2cb5f575d0c290549758cafe0e3b15acbca8c5163aa4209cbe4fb8fcb7de5"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "89988c8c1f16ca137c8e494f355eb42f974a19df118046e3338c95cf28a9095a"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "5564dbbe8adc0ba450afc6a1c3eef82f183a53ede5f3b1de0bc6ca320aadc5e9"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "ea877f00f3a8d3d075f5f05747884b69a0cc0339f6bde23313f6c4c317d14b9a"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d917697e84a95f857a447d26f94d93169a5a62176c93193cdf80c8d8bc1e280a"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "0cee4ba8e517cb73f6bb535a7ab8470d3131cb2c1be488a05891a3d89686ad63"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "f3c5cb21ff2e78c7e8cdbd14d1535e6edd464d5a436dbfa4e60b8ea91374674d"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "acc5199aefdbb418065cf4f3554693fcf9797dc1851a36ca7bad9e660b127763"
metafile = true

[[files]]
file = "mods/pandalib.pw.toml"
hash = "2c1d1804a4bd2380403214b42aec041847ba3aa6aa1bf7c12c07f81b2ab8f711"
metafile = true

[[files]]
file = "mods/pandas-falling-trees.pw.toml"
hash = "f5d434a0ddf59f5217ad141d3bdd8a61fecfdbf1f484d4ff3f6c84610b197a92"
metafile = true

[[files]]
file = "mods/particle-effects.pw.toml"
hash = "5c3a927717eaa6cb668e3d5c94f9d5e933fe49d7b26bfbc6acaadfce916bfe91"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
hash = "8980b8a6132621789579dc8bd4f0266be1bc53adde0d3e4565a58764cead0130"
metafile = true

[[files]]
file = "mods/pick-up-notifier.pw.toml"
hash = "af6de4e48064926264441ace0dc8f3193deedd534e2963c25a7700d4dfa6f825"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "2e2c1b47b513663871e71c89a699c66ac9fcc97633f007ed064ce4410f220f5a"
metafile = true

[[files]]
file = "mods/player-locator-plus.pw.toml"
hash = "95f470ffc8438ce15d252e73a959744af3eb699cc3e8458d975b1d20759606ce"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
hash = "f89967ea9150d6e5371057dc31fc8b8180c79808410ee6318088fcf78a16f58f"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
hash = "62df1cb449d5c6f8c5d670f14819a106a451e88102b8b066efeb73951f058d30"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "f013040d2544856ca9f8fe4e07e040aa8a78c87ace3426743a8429d73cba81a3"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "44a6662d6ac604b2173a8bc426a10c0d621c8ba99d37d1b72525c140c42cb358"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "55a727cabdd9d6e84fb0232b49d0dfa207751002e7f1f63b959baa35e2f29868"
metafile = true

[[files]]
file = "mods/respackopts.pw.toml"
hash = "6a9307b0c3b758faba13ab51388ccbb16ad2281bbd02c8e3655405fcdd7152fa"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "8302da862578554b012b2cfe58a3c1e75b514d09f94d842e7303be41a2157aeb"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "c8bda7e40ba3e14e7e78d1c1f80be842eb6d0acd21fca7b2e6a962bc810b9e46"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "cc98ef15cb0fb331703af145ea92255765247a2b1d27b87d05a44ad0dc6d9b4e"
metafile = true

[[files]]
file = "mods/skinrestorer.pw.toml"
hash = "1bb0f24b239a650d19698afc7d98d3e6298bd2bcf520eba0028991ceb685af70"
metafile = true

[[files]]
file = "mods/skinshuffle.pw.toml"
hash = "f0514cffe232d6c2f33b98176f0b61929caa91786547cda99a85dce28d65969f"
metafile = true

[[files]]
file = "mods/smooth-gui.pw.toml"
hash = "3cc2f693db80c6a53289e33028d7fec3029c7b8f6a1721f9b0e1141ef13e2397"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "1af09f16a643df0f61f2c799e981aa0b8c109999f0784584a6eff9a81f1c00c1"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "be0c8881821da897824770b2a71f0f3765a233eda69b295fa5b92ffe8a25014c"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "4ea85fa7d750bf5a167fe9652f2ac896d12ab068dacb8b04539e316ba5b74042"
metafile = true

[[files]]
file = "mods/subtle-effects.pw.toml"
hash = "c5677b5691588845f9ee31bd86ec1c578015e1f00387eb31f523af863ec11cfb"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "da7ee99189ad35aac094919fe33cac647d98533b23c228f10d4811f08989e2b8"
metafile = true

[[files]]
file = "mods/tooltip-overhaul.pw.toml"
hash = "3f150ae04e2e81105b1e98b3e4b4469d6365085743ff573da8dc716a00eccb41"
metafile = true

[[files]]
file = "mods/tpa.pw.toml"
hash = "da6df2dcc894fafc22896bca1bce1e2c89679134a72cd29031f27e685997a17a"
metafile = true

[[files]]
file = "mods/universal-graves.pw.toml"
hash = "695176ca996e639044d0d526cd6c56a95c9897e85e7a8119a2d14a712f755733"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "39426bfeeab22ea17f94fd3904dd9b78f9a3c9b4ddcb732b734ddbfd0e3568af"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "af20070dd9497817a83162c17b181a0a44f7213ea302d059a81c5aed02d0c877"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "64f90fd9619a092a8a5493d6ad9605bc5fec13f50f02feef1dcf47c9496a80bd"
metafile = true

[[files]]
file = "resourcepacks/mandalas-gui-dark-mode.pw.toml"
hash = "8ed45d3cf487c5ed8736050223b1b4211d79b44587031238afae1844199727cc"
metafile = true

[[files]]
file = "resourcepacks/stay-true.pw.toml"
hash = "34c7ffd73a82c57dcd6c7b90a1370546a78625e507c69a6f63e9849eec8e49d3"
metafile = true

[[files]]
file = "resourcepacks/tras-fresh-player.pw.toml"
hash = "32fe0fe8941110f8fba07ce7768faa1797de6b28e961ab65b483c380fc0a365a"
metafile = true

[[files]]
file = "resourcepacks/vanilla-exp.pw.toml"
hash = "1a041181d11ee578346f3da4e3de5f09db23d987aebc7b17281a8b506fc1dae3"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true
