hash-format = "sha256"

[[files]]
file = "mods/carry-on.pw.toml"
hash = "047ae8c0f28d98a9f35c5da633720f9f02cdaf4e452c7d836692613b0c798e18"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "d34fe1702f55920a19bcc18f03fa4402f39635c381c30277ad358d6e82577927"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "13ae813426f52226d8363499d722df0933e84534f216eef127c198c18bcdbb6b"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "45f268d205841b54991ff5a25e126f2ab314ff814f6f0ddeb26ac41ead4a7a09"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "278a349024e41e039f9f4a278532b56d1774cd2f7fde04f2cff298f3e085d995"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "b37d9f4fb121ed3f9e766cebf90007f9ed73cd082571772364deb6a05f8d2123"
metafile = true

[[files]]
file = "mods/cut-through.pw.toml"
hash = "57f102e8b398add66e7580de4a7f6ad1cf3d3f8722494d7ae14145aa217f33e4"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "2f3f7f7c169e820c8108fca57eae5d222d62783a725e979a87c78c1ba4c5cf82"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "f48fab32502e1db70e43ec5f2ebc05ab4c1b3a011c091489d372b4155316a381"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "12fe61275734cf8d2554d5f92af20ccb22479118b36a9a56a275ad3f4b1e13fb"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/fadeless.pw.toml"
hash = "49c4f17971d36db93c058db66b936988887a8f01b88766c83c2965d8ffa105d9"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "844fb8f081b3f6a0ecb1ca59bfeb643c7032d22fcefaac395108a22848d88b45"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "623f91f5cb2cfe0e7c3a6fc48ae5984dfad62e85389e2567ab5421f7d9d02c51"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "ced9729e413bbe2bd78889cbd3d3e93ae56b06c9728972a06ff03afe8a0f4eba"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "6cedc9c8d8bf132f0d6c2ebe8f943507c496be4ed1cee63288a7fafdcd3dd180"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "29bc0f585963a84e1f78af8a1ab779e34dcc4c1657190297bca9cd95aeb90d36"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "b1886358ebe6b6ff5f75c804687009ece51d89c90d8d8fc66cae128ae0b687dd"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "10d596c0e4f4ad44a20eb3a9eb0ea89d4ccdeee05a711d5e1bb04a032a4c1757"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "e94c47d7679c5a6a4a3deccaa7bba8f7c3961a70f6c03c32adc809d7135c87cc"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "c67921c4b888d1bc564ee09970b45716379f1b1e90c07c3f42d26b3d341359a4"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "799419e64ed42a8175333c541a08995fc4d84a2c6000877f60262fe55892e3ff"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
hash = "105169fbae392068873679af577312164b5746d00e22d51cd39fa18c6ae036eb"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "f1de93ef81913dabdd6a4848c5d9d868c41a0d3e8db3e78468b0c555ec139113"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "55a727cabdd9d6e84fb0232b49d0dfa207751002e7f1f63b959baa35e2f29868"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "fb3c7d111d903d281119cb66dcfd6e773f9b9a6a8e08d0796d7ee2b8162f6f71"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "c117f1abe6597e6c6da99a650072ff7d5d150d0f0d3267b4429f0d9b11c531dd"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "76785907b6a8484239e977cd91b3c94e49baa371d2bc6b51b691f30309cd2c8e"
metafile = true

[[files]]
file = "mods/skinrestorer.pw.toml"
hash = "b0a7e018095f64d3160a9b85295c33f92c5def6f4fefb87584ffdc1c6c603248"
metafile = true

[[files]]
file = "mods/skinshuffle.pw.toml"
hash = "fe345d23f71108cecbdac2d62fe29ac10f3494d59c5fa3849f9830f9a04ba652"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "abe9878dcb237d56e2ba70c17db8c721c6c2b8e62b241bc333539d5bc6be938f"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "700caca572649f238e804258f79d25969031be3e1b01d0384eb54a13200caba6"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "831c41448bccb5bb8f1f68a76321e7da7988b218e9694f432d952f98ac184640"
metafile = true

[[files]]
file = "mods/universal-graves.pw.toml"
hash = "18dd7240eb6cbeb69f31033ef45960e219c6a7abded9912423837ecaab1a3ddb"
metafile = true

[[files]]
file = "mods/vanilla-refresh.pw.toml"
hash = "c747d8ec64328f2722166ac62ea371cd5becf82fa4b8012a679092649046f5b4"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "64f90fd9619a092a8a5493d6ad9605bc5fec13f50f02feef1dcf47c9496a80bd"
metafile = true

[[files]]
file = "resourcepacks/stay-true.pw.toml"
hash = "ac5488193ee7485a8c107bfd43dfd7baf9e02f8bb34d82a648eb843ca50e8d6d"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true
