name = "KochMine"
author = "Vitor Koch"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c300f76d5db77899abdff8e7e6a698f12bbf68e2f38a96f12138ff94a22b88f9"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
