name = "KochMine"
author = "Vitor Koch"
version = "2.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cec4caf66a2d2a9503b77fbe8f1fccd0fedda6dabea895253c07b1359a65b5da"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
