name = "KochMine"
author = "Vitor Koch"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5fc215be5f9ee16ab957d6c12e1047f25229db7d9de29bf4ccbc1dc71fa8ced"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
