name = "KochMine"
author = "Vitor Koch"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c45904930605fedf14d32e1550e23b4c7a50a743e30c8bce4c4f02998ccdb45"

[versions]
fabric = "0.18.4"
minecraft = "1.21.5"
