name = "KochMine"
author = "Vitor Koch"
version = "2.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce41449261acea665bb3c145fe35b336cf44768afc691d2adc783e68a53f9e71"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
