name = "KochMine"
author = "Vitor Koch"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "574bd98f6443daf0def1635a3b6e34ac114b4ec6bacb926c1bbe2968613f8cf4"

[versions]
fabric = "0.18.4"
minecraft = "1.21.5"
