name = "KochMine"
author = "Vitor Koch"
version = "2.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4fe7fc7dba508936c42c67bc71cc3e4b4a61c26d649cabdce70d1124cc0ed0ff"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
