name = "KochMine"
author = "Vitor Koch"
version = "5.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f1915b5ac7ef8a65ba95e563d001372b611f42dc8f16f530d23e577006478af"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.2"]
