name = "KochMine"
author = "Vitor Koch"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8293830b452aa828e7aeae62bddeae2bb447d5859833aa8bed482fd5a7522d02"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
