name = "KochMine"
author = "Vitor Koch"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d55bd9e27aa9ff7be5935a60f476eb82d45077e8f2733e3fbad7dd88bd00aed3"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
