name = "KochMine"
author = "Vitor Koch"
version = "2.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e35252a217b8a540bc5ad5bd9a2e7559d4e52876c0d5e6dc33f4c80936e783dd"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
