name = "KochMine"
author = "Vitor Koch"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ae43f45528ce417d9c25d912e7339f8d596977a0eea8a01246c69ad8a729963"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
