name = "KochMine"
author = "Vitor Koch"
version = "5.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75d30b6d5b1301324ba03d90895a4a6fb867d724940fda443912f89b919ede74"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
